### ISSUE TITLE
Двойная экспозиция

### ISSUE THREAD

**Issue by Hutzo** [Hutzo/UX-UI-Design#10]

**Comment by Hutzo** [comment]
Практика двойной экспозиции/ Видео на ютубе и обработка фото ( не по образцу)![двойная экспозиция.jpg] заняло час (https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/c3ac317e-5755-4ce9-bf20-a1c2dd2f212d)

**Comment by Hutzo** [comment]
Еще 1 практика с двойной экспозицией. Вывод, нужны фото хорошего качества![колян.jpg](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/b09e3e90-a65b-491f-ae89-ef9ceacea7ba)

**Comment by Hutzo** [comment]
[Uploading... DSC_0089web.jpg.ceacba899f68f2dfb91004687afa5bef копия.jpg ]

**Comment by reoxidant** [comment]
выплатил 150 рублей
