### ISSUE TITLE
Баннер в Photoshop

### ISSUE THREAD

**Issue by Hutzo** [Hutzo/UX-UI-Design#14]

**Comment by Hutzo** [comment]
Добавить лого, навигационное меню. Сделано в ФШ потрачено **3 часа**. Все объекты вырезаны ![апельсиновые напитки главный экран.jpg](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/626c3c9b-caef-4cac-a7b1-58dd5490013b)

**Comment by Hutzo** [comment]
Законченный баннер. Общее время на работу 5 часов.![апельсиновые напитки баннер.jpg](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/02f5f7f1-501f-424f-bdeb-d62875aa40e2)

**Comment by reoxidant** [comment]
Переоценил 5 часов выставлены в 3 часа выполнений работы

**Comment by reoxidant** [comment]
выплатил 150 рублей
