### ISSUE TITLE
Создать лендинг коффетерия

### ISSUE THREAD

**Issue by Hutzo** [Hutzo/UX-UI-Design#49]

**Comment by Hutzo** [comment]
Задача состояла в том, чтобы набросить примерный дизайн сайта в Фигма и доработать в фотошопе.
На фигма потрачено час![Desktop - 1.png](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/f9837a11-8411-439f-b302-3b3e31cb7ae7) (незакончен)

**Comment by Hutzo** [comment]
Минимальный редизайн в фотошопе. ( потрачено в 2 раза больше времени (5 часов) стилистика хуже.![сайт про кофе.png](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/e96d6a93-9e6e-45eb-ac83-9921ac4b7071)

**Comment by Hutzo** [comment]
На данный момент финальная версия, возможно позже будет ресталлинг. 
**Выводы - начинать делать всё с прототипа, выбирать цвета, шрифты, тематику.**  Часа 2 на финалочку.![Landing_coffe.jpg](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/977f1862-8f04-4a78-afc2-7ef0f667e653)

**Comment by reoxidant** [comment]
Отличная работа!

**Comment by reoxidant** [comment]
Выплатил 400 рублей.
