### ISSUE TITLE
Интернет магазин одежды - выплачено

### ISSUE THREAD

**Issue by Hutzo** [Hutzo/UX-UI-Design#51]

**Comment by Hutzo** [comment]
Набросок интернет магазина одежды. Потрачено 2 часа![MacBook - 1.png](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/a8f5f777-782e-47b5-b3c5-a6bfa76af487)

**Comment by Hutzo** [comment]
Прототип карточки товара одежды. Поиск и рисовка 30 минут![карточка товара прототип.jpg](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/8aaec729-dd5c-4496-b0a2-fcac8d96fa39)

**Comment by Hutzo** [comment]
Редизайн сайта 2 часа.![РЕДИЗАЙН.png](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/f34a04ab-941a-478c-9037-0647f1bb9a5a)

**Comment by Hutzo** [comment]
Конечная стадия веб сайта. 2 часа![MacBo22221.png](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/ddb4c53c-4c46-477f-9d39-a2f5cb6944c4) 
В ближайшее время сделать **адаптивную версию и карточку товара**
![MacBo22221.png](https://images.zenhubusercontent.com/5fcb58a9f1d28ab9df2a426e/8e52852d-1ee4-43f2-9b0c-1872a495d9d1)

**Comment by reoxidant** [comment]
Отличный стиль, чуть доделать бы структуру. Выплатил 400 рублей.
